//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigCupPayroll.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BigCupPayrollEntities : DbContext
    {
        public BigCupPayrollEntities()
            : base("name=BigCupPayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Allowance> Allowances { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
    }
}
